apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: shreybatra/sample-backend
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_URI
          value: redis://redis-svc:6379

